<template>
  <b-row>
    <b-col></b-col>
    <b-col cols="6"
      ><h3 class="text-center mb-3">About Our Project</h3>
      <p>
        &nbsp; &nbsp; &nbsp; &nbsp; Motivated by the idea of reducing crime like
        the burglary happened recently around campus, our group decides to offer
        a new safety web application that provides a safety report and an
        inquiry functionality to advise residents for their daily life in
        Boston. We choose to look at Boston because we would like to look at a
        place with more sufficient data in order to develop a methodology for
        analyze crime data. For our safety report we will include the following
        feature:
      </p>
      <ol>
        <li>
          A Safety index of each district (Back Bay, Allston, Brighton, etc.)
          generated by a machine learning model to measure how safe that area
          is.
        </li>
        <li>
          Data visualizations on each necessary category like demographic data
          (i.e. percentage of male and female, breakdown of populations in terms
          of ages)
        </li>
        <li>
          Data visualization on the breakdowns of crime in the city (i.e. how
          environment affects criminal behaviors)
        </li>
      </ol>
      <p>
        Furthermore, in our inquiry functionality we will provide the following
        components for our user:
      </p>
      <ol>
        <li>
          Selection of each different category (i.e. region, season,
          temperature, weather)
        </li>
        <li>Return a simple query result</li>
      </ol>
      <p>
        We would divide our application into five different parts: Data
        Extraction, Data Analytics, Database Design, Front-end, and Back-end. In
        this proposal, we will explain the tasks and break down of each section.
      </p>
    </b-col>
    <b-col></b-col>
  </b-row>
</template>

<style scoped>
p{
  
}
</style>